spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
    host: localhost
    port: 9093
    group: main
    producers:
      main: main
  spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/${db}
      username: ${name}
      password: ${password}
    sql:
      init:
        schema-locations: classpath:schema.sql
        mode: always
